# Generated by Django 4.1.6 on 2023-02-01 19:04

from django.db import migrations, models
import ussd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('fields', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ussd_mental_health_providers',
            },
            bases=(models.Model, ussd.models.ExtraMixin),
        ),
        migrations.CreateModel(
            name='Psychiatrists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ussd_psychiatrists',
            },
            bases=(models.Model, ussd.models.ExtraMixin),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('website', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'ussd_resources',
            },
            bases=(models.Model, ussd.models.ExtraMixin),
        ),
        migrations.CreateModel(
            name='SessionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('menu_selection', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ussd_session_track',
            },
            bases=(models.Model, ussd.models.ExtraMixin),
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ussd_therapists',
            },
            bases=(models.Model, ussd.models.ExtraMixin),
        ),
    ]
